add_test([=[PodzbiorTest.Basic]=]  /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt/test_operacji [==[--gtest_filter=PodzbiorTest.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PodzbiorTest.Basic]=]  PROPERTIES WORKING_DIRECTORY /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RowneTest.Basic]=]  /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt/test_operacji [==[--gtest_filter=RowneTest.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RowneTest.Basic]=]  PROPERTIES WORKING_DIRECTORY /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RoznicaTest.Basic]=]  /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt/test_operacji [==[--gtest_filter=RoznicaTest.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RoznicaTest.Basic]=]  PROPERTIES WORKING_DIRECTORY /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SumaTest.Basic]=]  /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt/test_operacji [==[--gtest_filter=SumaTest.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SumaTest.Basic]=]  PROPERTIES WORKING_DIRECTORY /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SymTest.Basic]=]  /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt/test_operacji [==[--gtest_filter=SymTest.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SymTest.Basic]=]  PROPERTIES WORKING_DIRECTORY /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WspolnaTest.Basic]=]  /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt/test_operacji [==[--gtest_filter=WspolnaTest.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WspolnaTest.Basic]=]  PROPERTIES WORKING_DIRECTORY /home/students/k/u/kurowska/Desktop/JiNP/laby/zaj2/projekt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_operacji_TESTS PodzbiorTest.Basic RowneTest.Basic RoznicaTest.Basic SumaTest.Basic SymTest.Basic WspolnaTest.Basic)
